### ISSUE TITLE
What is the use of `/config`?

### ISSUE THREAD

**Issue by zwimer** [wiorca/docker-pia#1]
The `README.md` lists ways to mount config in and states:
> The home directory of docker_user, and where configuration files will live

What configuration files go here? I tried running this image with an empty directory here and nothing was ever written to this. Does `piactl` read from it somehow?

Or is this direction just meant so that the docker user can have persistence across restarts, and users can use it however they please?

**Comment by wiorca** [comment]
It's not really used in this image.  The original idea was to include an optional config file to define options as an alternative to env vars

You can omit it.
